China experienced a skyrocketing growth in its economy in the past 3 decades. The most obvious proof of China’s economic growth is shown through its GDP. From 1978 to 2013, China’s GDP increase on average of ten percent per year, making China now the second-largest economy in the world (Zhang, D., Li, X., & Xue, J., 2015). With a country's economic growth, citizens' life does have gotten better, such that people no longer have to worry about food shortages. However, economic growth does not mean everything in a country has gotten better, there is always a disadvantage side to an event. China's GDP has grown, this does not mean all of China has advanced. When China’s GDP is broken down by cities, it is shown that the main contributor to the high country’s GDP is from the 4 largest and developed cities, Beijing, Shanghai, Guangzhou, and Shenzhen. These four cities are known as beishangguangshen, meaning Beijing, Shanghai, Guangzhou, and Shenzhen. They are known to be advanced, where many people migrate to seek better opportunities, and these cities are known to have the highest real estate property prices. With such rapid development in a country, some factors did not catch up to such rapid growth. Education access and opportunity are unequally distrusted throughout China, creating education inequality across the country (Jain-Chandra, S., Khor, N., Mano, R., Schauer J., Wingender P., & Zhuang J., 2018). Data from 2010 compared China with major emerging markets and major advanced economics. The data shows that China has the highest percentage difference Urban-Rural gap, regional gap, and wealth gap among adults between the ages 25 and 29 (Jain-Chandra, S., Khor, N., Mano, R., Schauer J., Wingender P., & Zhuang J., 2018).  Even in such high GDP country, there is much inequality that has risen within the everyday citizens' community.

Big cities are known to be more advanced compared to less urban areas, and this applies true to China. These big cities are where many big companies would choose when locating their company, attracting more people to move to the city in hope of getting a job within the company. Many people see the opportunities in urban cities, many people would choose to migrate from rural areas to these urban cities in the hope to seek better opportunities. From a psychology perspective, social class is tied with education level, income, and occupation. To move up in the social class scale, high education level, high income, and high position occupation are all factors in moving up in a social class. Across the globe, most people are trying to climb up a level in the social class system. This also applies true to people in China, people would move to urban areas to seek a better job opportunity for themselves or education opportunities for the next generation. All three of these factors are what motivates the migration from urban to rural areas in China. In 2001 when China joined the WHO, it created a problem for rural households. Rural households have limited resources, which makes the cost to produce certain types of grain domestically to be greater than to import the grain(Gao, J., Liu, Y., Chen, J., & Cai, Y., 2019). Joining the WHO may sound nice, but it has created disadvantages for many rural families, enlarging the urban and rural gap (Gao, J., Liu, Y., Chen, J., & Cai, Y., 2019). As development can change living habits and standards of living, it does lead to unfreedom. People who would be against this development are people who are not gaining freedom from this development. The freedom to be against the markets is often against the unfreedom of the labor force, something that is extremely important to many people who rely on the labor force as a source of income.

Migration in China is not just moving to a new area and then one is automatically considered to be a person of that area. Migration happens in hoping to seek better opportunities, but with the hukou system in China, migration might not be as easy. Just simply moving to a different city does not make someone be that city person. The hukou system in China created a label for urban and rural area people, people are not distinguished of where they are from based on where they live, but where their hukou is. Hukou is a record where your family origin from, where your name is registered (Wu, X., 2011). Though it might just look like a little booklet with a page for each family member, it decides all your life chances (Wu, X., 2011). When a person is born, their parent’s hukou location determines their hukou location, the label they will have on them. Hukou in big cities often has more advantages than rural area’s hukou, such as more social benefits and access to education. Where your hukou is located decides what region of person you are, and where you can receive public education. For example, if a student’s family lives in Beijing, the student will need to meet the qualification to receive public education in Beijing(Wu, X., 2011). Unless a student attends a private institution, which is not something many households can afford. Even with migration, advanced education in big cities will always serve people of their region first. Who is not familiar with the hukou system might ask, can’t I just change my address? The answer to that is no, unlike the United States where you can just change your address to a different state when you move. To have a hukou in especially the four big cities, Beijing, Shanghai, Guangzhou, and Shenzen, you have to meet what is called qualifications. These qualifications included high education level, or high income (Chan, K. W., 2013). It’s extremely hard for ordinary people to meet these qualifications, making it hard to migrate from a rural region to an urban area within China (Chan, K. W., 2013). Between 1995 to 20000, where the main flow of migration occur between rural to urban (50.32 million) and between urban to urban regions (45.70 million) (Chan, K. W., 2013). The number from this migration data also includes what is called mobile migration, referring to people who live/work in a region but do not have their hukou in that area. Through the hukou system, we can also see the wealth gap. The wealthier family will meet qualifications to have the hukou in big cities, even if they do not, they are financially capable of sending their children to private institutions and even out of the country. This hukou system and regulation in China makes it harder to close the wealth gap, which wealth ties in with many other factors and opportunities. 

Many data is already showing the difference and unequal among regions in China, the government has yet to take successful action against it. The government has failed to recognize the problem of inequality across China. The Enrollment rate in school has increased since 1980, enrollment of rural children has been in the 90% range (ZHANG, X., & KANBUR, R., 2005). The enrollment rate has increased, but government contribution to education expense has decreased (ZHANG, X., & KANBUR, R., 2005). The decreased in the government budget for education, created an increase in out-of-pocket cost. Government budget percentage in education has been decreasing between 1990 and 1998, however, education expenditure has been increasing(ZHANG, X., & KANBUR, R., 2005). With income unequally distributed, it’s difficult for many families to afford education. Families with lower income might have more difficulties in supporting their children to finish the 9-year basic educations (ZHANG, X., & KANBUR, R., 2005). Some children might choose to start working before they even finish the 9-year basic education. These children that choose to stop receiving an education will create an education gap among the same age populations.
The view of development is expansive, there are many different ways one can approach development. Amartya Sen gives many different examples as to how development can be approach and why different countries develop differently. Every country is different in its way of living and physical location, just by simply looking at surface level data is not enough to see a countries development. To see the development of a country, Amartya Sen suggests looking at each point separately to fully understand the development.

Education is created by many which can factor that is linked to opportunities inequality, as phrased in Amartya Sen’s writing as unfreedom. Similar to Kander Mia’s situation of where he must go to work in a dangerous neighborhood. Kander Mia went to work in a neighborhood and ended up being physically injured. Though his wife told him to stay away from this dangerous neighborhood, he still decided to go. He risks this danger because of the need for money, the need for this job. His low income does not give him the freedom to choose where he wants to work, he would do any work that will pay him. He needs this money, his family needs this money. This situation is similar to students from lower-income families. A student might want to stay in school but because of the family's inability to pay for the education expense, the student would have no choice but to stop going to school and start working to help the family financially. These are just some factors of how someone can be financially unfree. Even in a high GDP country, not everyone can afford basic life necessities. When choosing between education or life necessities, life necessities would come first. 

Many limitations are limiting one from receiving a high education, resources, and wealth. Limitations can not be simply measured, as its difference among people. People might choose to attend up to undergraduate, higher than undergraduate, less than college, less than high school, or even less than secondary school. The reason why one might make such decisions is different among different people, but many are created by unfreedom. Unfreedom from time to further its education, unfreedom in opportunities, or unfreedom in money. The phrase chases your dream will always be a phrase. To chase your dream, you have to have full freedom. Though development helps us gain freedom, but can still at a time let us lose our freedom. Unfreedom still exists due to many different factors, some of which the same factor of development freedom. Development expands our freedom in many different factors, including economic and opportunities. Development isn't to be richer but to have more freedom. Freedom in different forms and points of view, the definition of freedom varies and there’s no one set definition for it. Freedom is defined by Amartya Sen’s as an action where you do not have to worry about a certain thing. To gain financial freedom would mean to have enough money to where you do not need to worry about money anymore. 
Through the improvement of a country, people are changing with it. 30 years ago when Shenzhen was just a place in the Guangdong province, no one would expected beishangguang (reference for the 3 big cities) to become beishangguangshen (the new reference for the major cities in China. What will happen in the next hour, next day is unpredictable, just like China's rapid economic growth. As these urban cities are advancing, people see them as opportunities to change their life. People in China move toward these urban areas in the hope to seek a change, this is what we call a geospatial data science methodology. They see the lacking education and opportunities in rural areas, so they choose to migrate into urban regions for more opportunities. Though not explicitly stated urban and rural gap leads to income inequality which will lead to education inequality. Education inequality is not simply created because of unequal resource distribution but also many other factors. Equal distribution of education across regions might not be as easy as just providing materials, but also teachers. Teachers have the right to choose where they work, they also have the right to decline if they are located in areas they do not want to work at. Meaning education inequality will always exist due to geographic location, family situations, and financial problems.



References
ZHANG, X., & KANBUR, R. (2005). Spatial inequality in education and health care in China. 
China Economic Review, 16(2), 189–204. https://doi.org/10.1016/j.chieco.2005.02.002
Wu, X. (2011). The Household Registration System and Rural-Urban Educational Inequality in 
Contemporary China. Chinese Sociological Review, 44(2), 31–51. 
https://doi.org/10.2753/csa2162-0555440202
Chan, K. W. (2013). China: internal migration. In The Encyclopedia of Global Human 
Migration. Blackwell Publishing Ltd. 
https://doi.org/10.1002/9781444351071.wbeghm124
Gao, J., Liu, Y., Chen, J., & Cai, Y. (2019). Demystifying the geography of income inequality in 
rural China: A transitional framework. Journal of Rural Studies. https://doi.org/10.1016/j.jrurstud.2019.01.010
Zhang, D., Li, X., & Xue, J. (2015). Education Inequality between Rural and Urban Areas of the 
People’s Republic of China, Migrants’ Children Education, and Some Implications. 
Asian Development Review, 32(1), 196–224. https://doi.org/10.1162/adev_a_00042
Sen, Amartya, 1933-. ( 2000). Development as freedom. New York :Anchor Books
